const { spawn } = require('child_process');
const path = require('path');
const { logger } = require('../../utils/logger');
const MeetingAssetsModel = require('../../models/MeetingAssetsModel');

class PythonBridge {
  /**
   * Internal helper to run a specific Python script from the engine folder.
   * @param {string} scriptName - The bridge file (e.g., 'bridge_media.py')
   * @param {string[]} args - Arguments for the script
   */
  static runStage(scriptName, args) {
    return new Promise((resolve, reject) => {
      const scriptPath = path.join(__dirname, '../engine/', scriptName);
      
      // '-u' flag forces Python to send output immediately (unbuffered)
      const pyProcess = spawn('python', ['-u', scriptPath, ...args], {
        env: { ...process.env, PYTHONUNBUFFERED: '1' },
        shell: true
      });

      let outputData = "";
      let errorData = "";

      // Captures every line Python prints in real-time
      pyProcess.stdout.on('data', (data) => {
        const str = data.toString();
        outputData += str;

        // Clean up the string and split into lines to handle rapid updates
        const lines = str.trim().split(/\r?\n/);
        lines.forEach(line => {
          if (line) {
            // This displays EVERYTHING in your terminal as it happens
            // We use a different color (Cyan) for the engine logs
            console.log(`\x1b[36m[${scriptName}]:\x1b[0m ${line}`);
            
            // Keep the logger informed too
            if (line.includes('[') || line.includes('%')) {
              logger.info(`[Engine] ${line}`);
            }
          }
        });
      });

      pyProcess.stderr.on('data', (data) => {
        const errStr = data.toString();
        errorData += errStr;
        // Print errors in Red immediately
        console.error(`\x1b[31m[Python Error]:\x1b[0m ${errStr.trim()}`);
      });

      pyProcess.on('close', (code) => {
        if (code === 0 && outputData.includes("SUCCESS")) {
          // Find the last line that contains SUCCESS to get the correct data
          const successLine = outputData.split('\n').find(l => l.includes("SUCCESS"));
          const result = successLine.split("|")[1].trim();
          resolve(result);
        } else {
          logger.error(`[Engine Error] ${scriptName} failed: ${errorData || 'Check Python Console'}`);
          reject(new Error(`Stage ${scriptName} failed with code ${code}`));
        }
      });
    });
  }

  /**
   * STAGE 1: Media Processing
   * Handles .mp4 (converts to .wav) or .mp3 (returns original path).
   */
  static async step1_Media(fileName) {
    logger.info(`[Bridge] Starting Stage 1: Media Check for ${fileName}`);
    return await this.runStage('bridge_media.py', [fileName]);
  }

  /**
   * STAGE 2: AI Pipeline
   * Runs Whisper & Pyannote. Receives audio path, returns transcript text.
   */
  static async step2_Transcription(audioPath) {
    logger.info(`[Bridge] Starting Stage 2: AI Pipeline (Whisper/Pyannote)`);
    return await this.runStage('bridge_pipeline.py', [audioPath]);
  }

  /**
   * STAGE 3: Educational Audit
   * Receives transcript text, returns JSON audit results.
   */
  static async step3_Audit(transcriptText) {
    logger.info(`[Bridge] Starting Stage 3: Educational Audit`);
    const result = await this.runStage('bridge_audit.py', [transcriptText]);
    return JSON.parse(result);
  }

  /**
   * A consolidated method that runs all steps but allows for per-stage failure handling.
   */
  static async runFullAudioPipeline(fileName) {
    try {
      // 1. Process Media (Extract if .mp4, else use .mp3)
      const audioPath = await this.step1_Media(fileName);

      // 2. Transcribe & Diarize
      const transcript = await this.step2_Transcription(audioPath);

      // 3. Audit Scoring
      const auditResults = await this.step3_Audit(transcript);

      const baseId = fileName.replace('REC_', '').split('.')[0];

      // 5. SAVE TO DATABASE
      // We map the Python results to the database columns
      await MeetingAssetsModel.saveAssets(baseId, {
        audio_path: audioPath,
        transcript_path: `storage/transcript/TRANS_${baseId}.txt`,
        audit_json_path: `storage/audits/AUDIT_${baseId}.json`,
        summary: auditResults.summary || "Summary generated by AI",
        oqi_score: auditResults.oqi_score
      });

      logger.info(`[Bridge] Database updated successfully for ${baseId}`);

      return {
        success: true,
        meeting_id: baseId,
        audioPath,
        transcript,
        auditResults
      };
    } catch (error) {
      logger.error(`[Bridge] Pipeline crashed: ${error.message}`);
      throw error;
    }
  }
}

module.exports = PythonBridge;